### ISSUE TITLE
No module named utils

### ISSUE THREAD

**Issue by javixeneize** [mwrlabs/needle#168]
## Issue
When running needle, i have an error in printer.py. Importerror:No module named 'utils'

I think the problem is that in your code, there is an utils.py, and there is also a python module called utils, so the tool can't open that class

Any suggestions on how to solve it? I think i need to force the app to search for utils in my directory instead of the python library folder

Thanks

Thanks

**Comment by marco-lancini** [comment]
In order to debug this issue, we require more information.

Ensure `VERBOSE` and `DEBUG` mode are enabled, this will provide us with more detailed needle logs:
```
[needle] > set VERBOSE True
VERBOSE => True
[needle] > set DEBUG True
DEBUG => True
```

Once you have this information, please attach the log files (starting from when you type `python needle.py`) to this thread and we can assist further.

**Comment by f-fly2** [comment]
Thats what i have

Traceback (most recent call last):
  File "needle.py", line 9, in <module>
    from core.framework import cli
  File "/Users/me/needle/needle/core/framework/cli.py", line 7, in <module>
    from ..utils.printer import Colors, Printer
  File "/Users/me/needle/needle/core/utils/printer.py", line 4, in <module>
    from utils import Utils
ImportError: No module named 'utils'

I cant enable verbose/debug mode as i cant even get into needle...

**Comment by marco-lancini** [comment]
What version are you using? From what branch?

**Comment by javixeneize** [comment]
Hi

The latest one from master -- https://github.com/mwrlabs/needle.git

**Comment by ccsplit** [comment]
@javixeneize, are you using Python3? (`python --version`) I've seen this issue within Python3, which I believe the imports may need to be changed in order to fully support Python3. I would suggest using Python 2.7.x in the meantime.

**Comment by javixeneize** [comment]
Hi

Im on python 2.7

Thanks

**Comment by marco-lancini** [comment]
As requested earlier, how are you launching it?

**Comment by javixeneize** [comment]
Just python needle.py

**Comment by marco-lancini** [comment]
sorry can't reproduce it with the information provided

**Comment by ccsplit** [comment]
@javixeneize and @f-fly2,

Can you please provide the following information from a command line: `python --version` and `pip freeze`. This will help determine if there are possibly issues with libraries conflicting, etc.

**Comment by javixeneize** [comment]
Hi

All sorted out now. The problem was that related to the naming, as ccsplit pointed out. Thats solved now

**Comment by marco-lancini** [comment]
@javixeneize can you please provide details?

**Comment by javixeneize** [comment]
Sure. What i did was to remove the external module that had the same name

**Comment by javedparmar** [comment]
@javixeneize: Can you please provide just 1 more step ahead insight. I am facing the same issue. And based on above statement, i guess I am very near to what it has been mention here.

I didn't get based on your last statement "remove the external module that had the same name"?

**Comment by javixeneize** [comment]
Hi

Not sure if i recall it correctly

The thing was that i had a library installed that had the same name as a
needle module. Python was trying to find the methods in that library
instead of in the needle module.

So, what i did was to remove the external library to avoid the naming issue

Hope it helps

**Comment by ccsplit** [comment]
Hello @javedparmar,

More than likely you have the [needle](https://pypi.python.org/pypi/needle) package installed. Which if you want to get the path of the file being imported you can obtain it by doing: `python -c "import needle; print needle.__file__"`. If you want to check to see if it is the other [needle](https://pypi.python.org/pypi/needle) you can try `pip freeze | grep needle` and if it appears it is more than likely the other needle package. Since I don't believe this package is on PyPi. You can also do `pip show needle` to see the details of the package if it shows up with `pip freeze | grep needle`.

The other needle will have the following information: 
```
Name: needle
Version: 0.5.0
Summary: Automated testing for your CSS.
Home-page: https://github.com/bfirsh/needle
Author: Ben Firshman
Author-email: ben@firshman.co.uk
License: UNKNOWN
Location: /Users/ccsplit/.virtualenvs/test/lib/python2.7/site-packages
Requires: selenium, pillow, nose
```

Hopefully that helps.
