### ISSUE TITLE
[!] 'NoneType' object has no attribute 'exec_command'

### ISSUE THREAD

**Issue by B4RD4k** [mwrlabs/needle#201]
Hey,
After running dependency_check module, i got this error. 
Please help
IOS 9.3.2
![image](https://user-images.githubusercontent.com/7777720/32894000-27a7e832-cae4-11e7-9cd9-52e3c5563f0f.png)

**Comment by marco-lancini** [comment]
In order to debug this issue, we require more information.

Ensure `VERBOSE` and `DEBUG` mode are enabled, this will provide us with more detailed needle logs:
```
[needle] > set VERBOSE True
VERBOSE => True
[needle] > set DEBUG True
DEBUG => True
```

Once you have this information, please attach the log files (starting from when you type `python needle.py`) to this thread and we can assist further.
