### ISSUE TITLE
Push command not working in ubuntu

### ISSUE THREAD

**Issue by pranavm2015** [mwrlabs/needle#255]
### Expected behaviour
Tell us what should happen.
File should push to device

### Actual behaviour
Tell us what happens instead.
No action occurs

### Steps to reproduce
1. Run push command with parameters

### needle error logs
Ensure verbose and debug mode are enabled:
```
[needle] > set VERBOSE True
VERBOSE => True
[needle] > set DEBUG True
DEBUG => True
```
No error logs arise.

#### Needle Version

- Framework (on your machine): 1.3.2
- Agent (on your device): 1.0.5

#### Workstation Operating System
Ubuntu

#### Python Version
2.7.12

#### Device iOS Version
10.3.3

#### Probable Fix
Add -> src = src.replace("'", "") 
After line 184 in /core/device/remote_operations.py

**Comment by marco-lancini** [comment]
In order to debug this issue, we require more information.

Ensure `VERBOSE` and `DEBUG` mode are enabled, this will provide us with more detailed needle logs:
```
[needle] > set VERBOSE True
VERBOSE => True
[needle] > set DEBUG True
DEBUG => True
```

Once you have this information, please attach the log files (starting from when you type `python needle.py`) to this thread and we can assist further.

**Comment by marco-lancini** [comment]
Closed due to inactivity
