### ISSUE TITLE
Configuration file displays the Password in cleartext

### ISSUE THREAD

**Issue by GeneralZero** [mwrlabs/needle#26]
## Issue
When loading the configuration from a file the password shows up on the screen.

### Expected behaviour
The password should be stored but the password should be starred out.

**Comment by marco-lancini** [comment]
Closing and moving it as a TODO in the _"New Features"_ kanban: https://github.com/mwrlabs/needle/projects/1

**Comment by tghosth** [comment]
Hi @marco-lancini 

Do you want me to have a look at this?

I can see the following places were a password will be displayed:
1) Setting password via a config file
2) Setting password manually 
3) Displaying option values
4) When a command string is printed to screen when using DEBUG logging.

See my suggest treatment below
1) From config:
`[needle] > set PASSWORD hunter2` >> Password should be starred out.
`PASSWORD => hunter2` >> Password should be starred out.

2) Manually
`[needle] > set PASSWORD hunter2` >> I don't see any sensible way of eliminating the password as the user has manually typed this in unless we do something crazy like [echo -e '\0033\0143'](http://superuser.com/a/123007)
`PASSWORD => hunter2` >> Password should be starred out.

3) Show options

```
Name           Current Value                 Required  Description
  -------------  -------------                 --------  -----------
  ...
  PASSWORD       hunter2                       yes       SSH Password of the testing device
```
Password should be starred out.

4) Output to debug.

I think this is the hardest one. I think the execute command functions need to take a parameter that indicates that indicates that a password is being passed (and what the password string is) so that it can be search/replaced out before being printed to debug log in a way which won't damage the rest of the command string.

As a general thing, do we want the starring out to be fixed (8 asterisks no matter what) or based on the password. E.g. hunter2 >> h******? Maybe this would be useful just for 1).

Interested in your thoughts on the above.

**Comment by marco-lancini** [comment]
1) Setting password via a config file: I agree with you, could be starred
2) Setting password manually: I'd leave it in clear text (for the user to check if it has entered correctly)
3) Displaying option values: definitely in clear text (the user needs to have a way to check if it's the correct one)
4) When a command string is printed to screen when using DEBUG logging: could be starred, but too complicated to implement.

I honestly don't think this is a "high" risk, therefore I'll leave it as it is now.
(even metasploit does not star out passwords...)

**Comment by tghosth** [comment]
Ok so I ended up doing some work on this before your comment and I have submitted a pull request #71 that requests the status below:

1) From config:
`[needle] > set PASSWORD hunter2` >> Can't star out password without fundamentally changing how underlying code libraries work so I have left this.
`PASSWORD => hunter2` >> Password starred out.

2) Manually
`[needle] > set PASSWORD hunter2` >> Can't star out password without fundamentally changing how underlying code libraries work so I have left this.
`PASSWORD => hunter2` >> Password starred out.

3) Show options

```
Name           Current Value                 Required  Description
  -------------  -------------                 --------  -----------
  ...
  PASSWORD       hunter2                       yes       SSH Password of the testing device
```
So I have starred out the password here because if a user really wants to make sure it is right, they can just set it again. I can revert that out if you want.

4) Output to debug. 
As noted, difficult to implement so I have left this for now.
