### ISSUE TITLE
 Exception: sh: lipo: command not found.

### ISSUE THREAD

**Issue by AloneMonkey** [mwrlabs/needle#84]
### needle error logs
Ensure verbose and debug mode are enabled:
```
[needle][pull_ipa] > run
[*] Checking connection with device...
[+] Already connected to: 127.0.0.1
[V] Creating temp folder: /var/root/needle/
[+] Target app: com.toyopagroup.picaboo
[*] Retrieving app's metadata...
[!] Exception: sh: lipo: command not found.
```

**Comment by marco-lancini** [comment]
Hi @AloneMonkey, try to see if this solve the issue: #70

**Comment by AloneMonkey** [comment]
`set SETUP_DEVICE True` but some package install failed,  and still run with error

```
[?] Trying to continue anyway...
[+] Target app: xxxxxx
[*] Retrieving app's metadata...
[!] Exception: sh: lipo: command not found.
```

which package this tool in?

**Comment by marco-lancini** [comment]
can you post the full error log (enabling `set DEBUG True` first), so I can try troubleshoot it please?
Anyway, you should be able to find `lipo` in: `org.coolstar.cctools`

**Comment by Lavikw** [comment]
I have the same issue. I used SETUP_DEVICE and there were some errors in the setup. 

Attached is the log: 
[V] Setting up SSH connection...
[+] Connected to: 127.0.0.1
[V] Creating temp folder: /var/root/needle/
[D] [REMOTE CMD] Remote Command: if [ -d /var/root/needle/ ]; then echo "yes"; else echo "no" ; fi
[*] Configuring device...
[D] [REMOTE CMD] Remote Command: which apt-get
[D] [REMOTE CMD] Remote Command: which dpkg
[D] [REMOTE CMD] Remote Command: apt-get update
[?] Error occurred during apt-get update: W: GPG error: http://repo.nesolabs.de ./ Release: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY F5266226F1ADFFA2
W: GPG error: http://cydia.hbang.ws ./ Release: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 5D3B26B3D58C7D91
[?] Trying to continue anyway...
[V] [INSTALL] Installing COREUTILS via apt-get.
[D] [REMOTE CMD] Remote Command: apt-get install -y --force-yes coreutils
[V] [INSTALL] Installing COREUTILS via apt-get.
[D] [REMOTE CMD] Remote Command: apt-get install -y --force-yes coreutils-bin
[D] [REMOTE CMD] Remote Command: dpkg --get-selections | grep -v "deinstall" | cut -f1
[D] [REMOTE CMD] Remote Command: apt-get update
[?] Error occurred during apt-get update: W: GPG error: http://repo.nesolabs.de ./ Release: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY F5266226F1ADFFA2
W: GPG error: http://cydia.hbang.ws ./ Release: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 5D3B26B3D58C7D91
[?] Trying to continue anyway...
[D] [REMOTE CMD] Remote Command: cat /etc/apt/sources.list.d/cydia.list
[D] [REMOTE CMD] Remote Command: which FileDP
[D] [INSTALL] Tool already available: FILEDP
[V] [INSTALL] Installing ONDEVICECONSOLE via apt-get.
[D] [REMOTE CMD] Remote Command: apt-get install -y --force-yes com.eswick.ondeviceconsole
[?] Error occurred during installation of tools: dpkg: serious warning: files list file for package `apt.3k.app.weiphone.appsyncunified.fengsync8' missing, assuming package has no files currently installed.

dpkg: serious warning: files list file for package `apr-lib' missing, assuming package has no files currently installed.

dpkg: serious warning: files list file for package `com.saurik.substrate.safemode' missing, assuming package has no files currently installed.

dpkg: serious warning: files list file for package `apt.3k.taigafc2' missing, assuming package has no files currently installed.
[?] Trying to continue anyway...
[D] [REMOTE CMD] Remote Command: which keychain_dump
[D] [INSTALL] Tool already available: KEYCHAIN_DUMP
[V] [INSTALL] Installing OPEN via apt-get.
[D] [REMOTE CMD] Remote Command: apt-get install -y --force-yes com.conradkramer.open
[?] Error occurred during installation of tools: dpkg: serious warning: files list file for package `apt.3k.app.weiphone.appsyncunified.fengsync8' missing, assuming package has no files currently installed.

dpkg: serious warning: files list file for package `apr-lib' missing, assuming package has no files currently installed.

dpkg: serious warning: files list file for package `com.saurik.substrate.safemode' missing, assuming package has no files currently installed.

dpkg: serious warning: files list file for package `apt.3k.taigafc2' missing, assuming package has no files currently installed.
[?] Trying to continue anyway...
[D] Installation method not provided for UIOPEN. Skipping
[V] [INSTALL] Manually installing: SSLKILLSWITCH
[D] [REMOTE CMD] Remote Command: curl -ksL "https://github.com/iSECPartners/ios-ssl-kill-switch/releases/download/release-0.6/com.isecpartners.nabla.sslkillswitch_v0.6-iOS_7.0.deb" -o /var/root/kill.deb
[D] [REMOTE CMD] Remote Command: dpkg -i /var/root/kill.deb && rm -f /var/root/kill.deb
[?] Error occurred during installation of tools: dpkg: serious warning: files list file for package `apt.3k.app.weiphone.appsyncunified.fengsync8' missing, assuming package has no files currently installed.

dpkg: serious warning: files list file for package `apr-lib' missing, assuming package has no files currently installed.

dpkg: serious warning: files list file for package `com.saurik.substrate.safemode' missing, assuming package has no files currently installed.

dpkg: serious warning: files list file for package `apt.3k.taigafc2' missing, assuming package has no files currently installed.
dpkg: dependency problems prevent configuration of com.isecpartners.nabla.sslkillswitch:
 com.isecpartners.nabla.sslkillswitch depends on preferenceloader; however:
  Package preferenceloader is not installed.
dpkg: error processing com.isecpartners.nabla.sslkillswitch (--install):
 dependency problems - leaving unconfigured
Errors were encountered while processing:
 com.isecpartners.nabla.sslkillswitch
[?] Trying to continue anyway...
[V] [INSTALL] Installing SOCAT via apt-get.
[D] [REMOTE CMD] Remote Command: apt-get install -y --force-yes socat
[?] Error occurred during installation of tools: E: Unmet dependencies. Try 'apt-get -f install' with no packages (or specify a solution).
[?] Trying to continue anyway...
[D] Installation method not provided for LIPO. Skipping
[D] [INSTALL] Already installed: COREUTILS.
[D] [INSTALL] Already installed: COREUTILS.
[D] [INSTALL] Already installed: PLUTIL.
[D] Installation method not provided for WHICH. Skipping
[V] [INSTALL] Installing FRIDA via apt-get.
[D] Adding repo to cydia.list: https://build.frida.re/
[D] [REMOTE CMD] Remote Command: echo "deb https://build.frida.re/ ./" >> /etc/apt/sources.list.d/cydia.list
[D] [REMOTE CMD] Remote Command: apt-get update
[?] Error occurred during apt-get update: W: GPG error: http://repo.nesolabs.de ./ Release: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY F5266226F1ADFFA2
W: GPG error: http://cydia.hbang.ws ./ Release: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 5D3B26B3D58C7D91
[?] Trying to continue anyway...
[D] [REMOTE CMD] Remote Command: apt-get install -y --force-yes re.frida.server
[?] Error occurred during installation of tools: E: Unmet dependencies. Try 'apt-get -f install' with no packages (or specify a solution).
[?] Trying to continue anyway...
[D] Installation method not provided for APT-GET. Skipping
[V] [INSTALL] Manually installing: THEOS
[D] [REMOTE CMD] Remote Command: ln -s /usr/local/bin/perl /usr/bin/perl
[?] Error occurred during installation of tools: ln: failed to create symbolic link `/usr/bin/perl': File exists
[?] Trying to continue anyway...
[D] [REMOTE CMD] Remote Command: which pbwatcher
[D] [INSTALL] Tool already available: PBWATCHER
[V] [INSTALL] Installing IPAINSTALLER via apt-get.
[D] [REMOTE CMD] Remote Command: apt-get install -y --force-yes com.autopear.installipa
[?] Error occurred during installation of tools: E: Unmet dependencies. Try 'apt-get -f install' with no packages (or specify a solution).
[?] Trying to continue anyway...
[D] Installation method not provided for FIND. Skipping
[D] Installation method not provided for DPKG. Skipping
[V] [INSTALL] Installing CLUTCH via apt-get.
[D] Adding repo to cydia.list: http://cydia.iphonecake.com/
[D] [REMOTE CMD] Remote Command: echo "deb http://cydia.iphonecake.com/ ./" >> /etc/apt/sources.list.d/cydia.list
[D] [REMOTE CMD] Remote Command: apt-get update
[?] Error occurred during apt-get update: W: GPG error: http://repo.nesolabs.de ./ Release: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY F5266226F1ADFFA2
W: GPG error: http://cydia.hbang.ws ./ Release: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 5D3B26B3D58C7D91
[?] Trying to continue anyway...
[D] [REMOTE CMD] Remote Command: apt-get install -y --force-yes com.iphonecake.clutch2
[?] Error occurred during installation of tools: E: Unmet dependencies. Try 'apt-get -f install' with no packages (or specify a solution).
[?] Trying to continue anyway...
[D] Installation method not provided for OTOOL. Skipping
[D] Installation method not provided for UNZIP. Skipping
[D] [REMOTE CMD] Remote Command: which fsmon
[D] [INSTALL] Tool already available: FSMON
[V] [INSTALL] Installing DARWINTOOLS via apt-get.
[D] [REMOTE CMD] Remote Command: apt-get install -y --force-yes org.coolstar.cctools
[?] Error occurred during installation of tools: E: Unmet dependencies. Try 'apt-get -f install' with no packages (or specify a solution).
[?] Trying to continue anyway...
[V] [INSTALL] Installing CYCRIPT via apt-get.
[D] [REMOTE CMD] Remote Command: apt-get install -y --force-yes cycript
[?] Error occurred during installation of tools: E: Unmet dependencies. Try 'apt-get -f install' with no packages (or specify a solution).
[?] Trying to continue anyway...
[D] [INSTALL] Already installed: GDB.
[V] [INSTALL] Installing PERL via apt-get.
[D] Adding repo to cydia.list: http://coolstar.org/publicrepo/
[D] [REMOTE CMD] Remote Command: echo "deb http://coolstar.org/publicrepo/ ./" >> /etc/apt/sources.list.d/cydia.list
[D] [REMOTE CMD] Remote Command: apt-get update
[?] Error occurred during apt-get update: W: GPG error: http://repo.nesolabs.de ./ Release: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY F5266226F1ADFFA2
W: GPG error: http://cydia.hbang.ws ./ Release: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 5D3B26B3D58C7D91
[?] Trying to continue anyway...
[D] [REMOTE CMD] Remote Command: apt-get install -y --force-yes org.coolstar.perl
[?] Error occurred during installation of tools: E: Unmet dependencies. Try 'apt-get -f install' with no packages (or specify a solution).
[?] Trying to continue anyway...
[D] [INSTALL] Already installed: BIGBOSS.
[D] Installation method not provided for STRINGS. Skipping
[V] [INSTALL] Installing CLASS-DUMP via apt-get.
[D] [REMOTE CMD] Remote Command: apt-get install -y --force-yes pcre
[?] Error occurred during installation of tools: E: Unmet dependencies. Try 'apt-get -f install' with no packages (or specify a solution).
[?] Trying to continue anyway...
[D] Installation method not provided for THEOS_NIC. Skipping
[D] [INSTALL] Already installed: LDID.
[V] [INSTALL] Installing PREFERENCELOADER via apt-get.
[D] [REMOTE CMD] Remote Command: apt-get install -y --force-yes preferenceloader
[?] Error occurred during installation of tools: dpkg: serious warning: files list file for package `apt.3k.app.weiphone.appsyncunified.fengsync8' missing, assuming package has no files currently installed.

dpkg: serious warning: files list file for package `apr-lib' missing, assuming package has no files currently installed.

dpkg: serious warning: files list file for package `com.saurik.substrate.safemode' missing, assuming package has no files currently installed.

dpkg: serious warning: files list file for package `apt.3k.taigafc2' missing, assuming package has no files currently installed.
[?] Trying to continue anyway...
[*] Target app not selected. Launching wizard...
[D] [REMOTE CMD] Remote Command: if [ -f /var/mobile/Library/MobileInstallation/LastLaunchServicesMap.plist ]; then echo "yes"; else echo "no" ; fi
[V] Refreshing list of installed apps...
[D] [REMOTE CMD] Remote Command: /bin/su mobile -c /usr/bin/uicache
[D] Copy the plist to temp: /var/mobile/Library/MobileInstallation/LastLaunchServicesMap.plist -> /var/root/needle/LastLaunchServicesMap.plist
[D] [REMOTE CMD] Remote Command: cp /var/mobile/Library/MobileInstallation/LastLaunchServicesMap.plist /var/root/needle/LastLaunchServicesMap.plist
[D] Converting plist to XML: /var/root/needle/LastLaunchServicesMap.plist
[D] [REMOTE CMD] Remote Command: plutil -convert xml1 /var/root/needle/LastLaunchServicesMap.plist
[D] Extracting content from: /var/root/needle/LastLaunchServicesMap.plist
[D] [REMOTE CMD] Remote Command: cat /var/root/needle/LastLaunchServicesMap.plist
[D] Parsing plist content
[+] Apps found:
		0 - com.gettaxi.iphone
		1 - com.ubercab.UberClient
[>][QUESTION] Please select a number:

**Comment by marco-lancini** [comment]
Hi @AloneMonkey, did you manage to solve the issue?

**Comment by marco-lancini** [comment]
closed due to inactivity

**Comment by poldenais** [comment]
Hi Marco, I'm getting the same message now. Was there a solution? Have the coolstar repo installed on the JB iPad.

**Comment by cobbr** [comment]
I am experiencing this issue, and the previous solution to use the coolstar repo no longer appears to work. Additionally, using SETUP_DEVICE does not automatically install this.

```
[needle] > set DEBUG True
DEBUG => True
[needle] > set VERBOSE True
VERBOSE => True
[needle] > set SETUP_DEVICE True
SETUP_DEVICE => True
[needle] > use binary/info/metadata
[needle][metadata] > run
[*] Checking connection with device...
[+] Already connected to: 127.0.0.1
[D] Creating temp folder: /var/root/needle/
[D] [REMOTE CMD] Remote Command: if [ -d /var/root/needle/ ]; then echo "yes"; else echo "no" ; fi
[+] Target app: com.highaltitudehacks.dvia
[*] Retrieving app's metadata...
/private/var/containers/Bundle/Application/801DC9B4-CD5E-4A6B-BD00-B25A15BF0560/DamnVulnerableIOSApp.app/Info.plist
[D] Copying the plist to temp: /private/var/containers/Bundle/Application/801DC9B4-CD5E-4A6B-BD00-B25A15BF0560/DamnVulnerableIOSApp.app/Info.plist -> /root/.needle/tmp/plist
[*] Pulling: /private/var/containers/Bundle/Application/801DC9B4-CD5E-4A6B-BD00-B25A15BF0560/DamnVulnerableIOSApp.app/Info.plist -> /root/.needle/tmp/plist
[D] Downloading: "/private/var/containers/Bundle/Application/801DC9B4-CD5E-4A6B-BD00-B25A15BF0560/DamnVulnerableIOSApp.app/Info.plist" -> /root/.needle/tmp/plist
[D] [LOCAL CMD] Local Command: sshpass -p <removed> scp -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -P 2222 root@127.0.0.1:"/private/var/containers/Bundle/Application/801DC9B4-CD5E-4A6B-BD00-B25A15BF0560/DamnVulnerableIOSApp.app/Info.plist" /root/.needle/tmp/plist
[D] [REMOTE CMD] Remote Command: lipo -info /private/var/containers/Bundle/Application/801DC9B4-CD5E-4A6B-BD00-B25A15BF0560/DamnVulnerableIOSApp.app/DamnVulnerableIOSApp
------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/needle/needle/core/framework/module.py", line 111, in do_run
    pre = self.module_pre()
  File "/opt/needle/needle/core/framework/module.py", line 147, in module_pre
    if self.app_check() is None: return None
  File "/opt/needle/needle/core/framework/framework.py", line 665, in app_check
    self.APP_METADATA = Framework.APP_METADATA = self.device.app.get_metadata(app)
  File "/opt/needle/needle/core/device/app.py", line 19, in get_metadata
    return self._retrieve_metadata()
  File "/opt/needle/needle/core/device/app.py", line 40, in _retrieve_metadata
    architectures = self.__detect_architectures(binary_path)
  File "/opt/needle/needle/core/device/app.py", line 111, in __detect_architectures
    out = self._device.remote_op.command_blocking(cmd, internal=True)
  File "/opt/needle/needle/core/device/remote_operations.py", line 94, in command_blocking
    out, err = self._device._exec_command_ssh(cmd, internal)
  File "/opt/needle/needle/core/device/device.py", line 128, in _exec_command_ssh
    raise Exception(err_str)
Exception: sh: lipo: command not found

------------------------------------------------------------
[!] Exception: sh: lipo: command not found.
```

**Comment by marco-lancini** [comment]
Hi @cobbr, you can find `lipo` in the `org.coolstar.cctools` package (which is among the ones automatically installed by needle)

**Comment by JoelPagliuca** [comment]
I am also experiencing this, possibly worth noting the Cydia package required in the docs?

**Comment by marco-lancini** [comment]
Hi, please refer to this comment: https://github.com/mwrlabs/needle/issues/164#issuecomment-319109577
